name: Run autotest


on: 
  workflow_dispatch:
    deployment_target:
      description: select tests to run
      required: true
      type: choice
      default: all
      options:
        - all

jobs: 
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Copy sourse code
        uses: actions/checkout@v4.2.2
      - name: Set up Python environment
        uses: actions/setup-python@v5.3.0
        with: 
          python-version: "3.13.0"
      - name: install dependencies
          run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
